name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir data || true
      - run: npm install
      - run: node bin/build.js 1
      - run: cat data/latest_v2.csv | wc -l
      - run: sed -e "s|$address_count|10000|g" README.md
      - run: node bin/build-api.js staging
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Deploy generated files
        working-directory: gh-pages
        run: |
          rm -rf staging-api
          mv ../build/staging-api .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add staging-api > /dev/null 2>&1
          git commit -m "Deploy" > /dev/null 2>&1
          git push origin gh-pages
          git checkout master
          sed -i -e "s|\${address_count}|10000|g" README.md
          git add README.md > /dev/null 2>&1
          git commit -m "Update address count" > /dev/null 2>&1
          git push origin master
