name: Deploy
on:
  push:
    branches:
      - develop
    tags:
      - "releases/*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - run: echo 'test'
