name: Deploy
on:
  push:
    branches:
      - develop
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - run: npm install
      - run: node bin/build.js 2
      - run: node bin/build-api.js staging
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Deploy generated files
        working-directory: gh-pages
        run: |
          rm -rf staging-api
          mv ../build/staging-api .
