name: Deploy
on:
  push:
    branches:
      - develop
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: mkdir data
      - run: npm install
      - run: node bin/build.js 2
      - run: node bin/build-api.js staging
      - name: Deploy generated files
        run: |
          git checkout gh-pages
