name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Deploy generated files
        working-directory: gh-pages
        run: |
          touch staging-api/aaa
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add staging-api > /dev/null 2>&1
          git commit -m "Deploy" > /dev/null 2>&1
          git push origin gh-pages
          git checkout master
          sed -i -e "s|\${address_count}|10000|g" README.md
          git add README.md > /dev/null 2>&1
          git commit -m "Update address count" > /dev/null 2>&1
          git push origin master
